"""assemble_training_segments.py -- download + assemble training segments.

mostly PHerc0139 fragments, plus a PHerc0814 segment (seg46527). the surface-volume URL
and its raw-volume id differ per scroll, so the 9.362um volume name is overridable per
fragment via FRAG_OPTS['vol9_name'] (defaults to the PHerc0139 constant VOL9_NAME).

per fragment, in order (each step skips if its output already exists):
  1. download 9.362um surface volume (level 0)  -> ves_zarrs2/<id>.zarr + masks/<id>.png
  2. verify eroded_inklabels/<id>.png exists (pre-generated conservative binary labels;
     these must exist before training -- warns in red if missing)
  3. precompute normalization stats

NOTE: eroded_inklabels are NOT generated by this script. they are pre-generated from
1um ink detection, thresholded high (>0.55), eroded 3x3, and masked. the inklabels/
directory (raw 1um ink detection) is not used during training.

usage:
  python assemble_training_segments.py --only w058          # one fragment (pilot)
  python assemble_training_segments.py                       # all fragments
  python assemble_training_segments.py --from w039           # resume from a fragment
  python assemble_training_segments.py --skip-norm           # skip the (slow) norm precompute
"""
from __future__ import annotations
import argparse, json, os, shutil, subprocess, sys, time
from concurrent.futures import ThreadPoolExecutor
import numpy as np
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

BUCKET = "https://vesuvius-challenge-open-data.s3.amazonaws.com"
# output zarr dir: honor $VESUVIUS_ZARR_PATH (same var config/precompute read); default is
# /vesuvius/ves_zarrs2 on linux, the local documents path on windows.
ZARR_DIR = os.getenv("VESUVIUS_ZARR_PATH",
                     "/vesuvius/ves_zarrs2" if os.name == "posix"
                     else r"C:\Users\ChenJeff\Documents\ves_zarrs2")
TMP = "_ves_tmp"

# constant across all PHerc0139 segments
# constant across all PHerc0139 segments
VOL9_NAME = "9.362um-1.2m-113keV-volume-20250728140407.zarr"

# (name, segment_prefix, zarr_id)
SEGMENTS = [
    # original 4 training fragments. their eroded labels + masks are already final,
    # so skip_labels=True keeps those and only (re)fetches the surface volume + norm.
    # w056 was mesh-rendered (not a pre-rendered surface-volume) -- its zarr already
    # exists so step1 skips; a fresh repro of w056 needs old/render_9um_surface.py.
    ("w044", "PHerc0139/segments/20260115000000-w044_2026011522", "20260115000000"),
    ("w059", "PHerc0139/segments/20250223000000-w059_2025022312", "20250223000000"),
    ("w047", "PHerc0139/segments/20260206000001-w047_2026020613", "20260206000001"),
    ("w056", "PHerc0139/segments/20260115000001-w056_2026011514", "20260115000001"),
    # 10 new training fragments (2026-07-21)
    ("w058", "PHerc0139/segments/20260210000000-w058_2026021020", "20260210000000"),
    ("w052", "PHerc0139/segments/20260227000000-w052_2026022705", "20260227000000"),
    ("w049", "PHerc0139/segments/20260318000000-w049_20260318",   "20260318000000"),
    ("w046", "PHerc0139/segments/20260325000000-w046_20260325",   "20260325000000"),
    ("w041", "PHerc0139/segments/20260108000000-w041_2026010816", "20260108000000"),
    ("w040", "PHerc0139/segments/20250831000000-w040_2025083102", "20250831000000"),
    ("w039", "PHerc0139/segments/20260302000000-w039_2026030210", "20260302000000"),
    ("w038", "PHerc0139/segments/20260306000000-w038_2026030608", "20260306000000"),
    ("w037", "PHerc0139/segments/20260310000000-w037_2026031015", "20260310000000"),
    ("w034", "PHerc0139/segments/20260303000000-w034_2026030317", "20260303000000"),
    # PHerc0139 w035 (2026-08-12). inklabels downloaded via download_w035_labels.py.
    ("w035", "PHerc0139/segments/20260317000000-w035_2026031718", "20260317000000"),
    # HOLDOUT sanity fragment -- assembled but NOT added to DEFAULT_SCROLLS. exclusive
    # hallucination check: if inference on w055 doesn't match its 1.1um text, we hallucinated.
    ("w055", "PHerc0139/segments/20251226000000-w055_2025122611", "20251226000000"),
    # PHerc0814 segment (2026-07-22). DIFFERENT scroll -> different surface-volume name
    # (raw vol 20250804134230, see FRAG_OPTS['vol9_name']). only mask + eroded label exist
    # (no non-eroded 1um ink), so skip_labels keeps those and just fetches the zarr + norm.
    ("seg46527", "PHerc0814/segments/20260226000000-46527_2um_try2", "20260226000000"),
    # PHerc0500P2 front segment (2026-08-07). DIFFERENT scroll, same resolution/energy as
    # PHerc0139 (9.362um/113keV/1.2m). crystal-clear 2.215um inklabels available, making
    # this a high-quality training fragment from a new scroll domain.
    ("500P2_front", "PHerc0500P2/segments/20250628074500-500P2_front", "20250628074500"),
    # PHerc1667 w013 (2026-08-13). assembled via assemble_w013_1667.py (level-2 surface zarr
    # at 2.399um, z-pooled 109->28 layers, left 25% crop). shape: (28, 10400, 4975) ~9.6um.
    ("w013", "PHerc1667/segments/20240304141531-w013_20240304141531_flatboi", "20240304141531"),
]

# per-fragment behaviour overrides. skip_labels=True skips the eroded label check
# (for fragments whose labels are already verified present and final).
FRAG_OPTS = {
    "w044": {"skip_labels": True},
    "w059": {"skip_labels": True},
    "w047": {"skip_labels": True},
    "w056": {"skip_labels": True},
    "w055": {"holdout": True},
    # PHerc0814: its surface volume is a different raw scan than the PHerc0139 constant,
    # and its labels are already final (eroded only), so keep them and only fetch the zarr.
    "seg46527": {"skip_labels": True,
                 "vol9_name": "9.362um-1.2m-113keV-volume-20250804134230.zarr"},
    # PHerc0500P2: different raw volume name from PHerc0139 constant.
    # inklabels will be generated separately (download_p500p2_labels.py) from the
    # 2.215um ink detection TIF and saved to inklabels/ and eroded_inklabels/.
    "500P2_front": {"vol9_name": "9.362um-1.2m-113keV-volume-20250820143440.zarr"},
    # PHerc1667 w013: assembled via a dedicated script (pre-rendered level-2 surface zarr,
    # z-pooled to 28 layers). skip_labels=True because inklabels are generated by that script.
    "w013": {"skip_labels": True, "custom_assemble": True},
}

CHUNK_XY = 128     # S3 surface volume source chunks are 128x128

# OUTPUT zarr chunk sizes (default optimized for 48x48 context, 16x16 tiles, 8-slice windows)
DEFAULT_CHUNK_DEPTH = 8   # matches 8-slice depth windows in triple mode
DEFAULT_CHUNK_Y = 32      # 2x tile_size, reasonable cache granularity
DEFAULT_CHUNK_X = 32      # 2x tile_size, reasonable cache granularity


def run(cmd):
    print(f"  $ {' '.join(cmd)}", flush=True)
    r = subprocess.run(cmd)
    if r.returncode != 0:
        raise RuntimeError(f"command failed ({r.returncode}): {' '.join(cmd)}")


def _pbar(total, desc):
    """progress reporter: a real tqdm bar if tqdm is importable, else periodic percent prints.
    returns (update, close) callables so the caller doesn't care which backend is used."""
    try:
        from tqdm import tqdm
        bar = tqdm(total=total, desc=f"[dl] {desc}", unit="it")
        return (lambda n=1: bar.update(n)), bar.close
    except Exception:
        st = {"n": 0}
        step = max(1, total // 10)
        def upd(n=1):
            st["n"] += n
            if st["n"] % step == 0 or st["n"] >= total:
                print(f"[dl] {desc} {st['n']}/{total}", flush=True)
        return upd, (lambda: None)


def _get_json(url):
    r = subprocess.run(["curl", "-s", "--fail", "--max-time", "60", url], capture_output=True)
    if r.returncode != 0:
        raise RuntimeError(f"failed to fetch {url}")
    return json.loads(r.stdout.decode("utf-8"))


def _curl_code(url, out, tries=3):
    """curl one url -> out, returning the HTTP status code as a string. retries TRANSIENT
    failures (5xx / timeout / connection reset) with backoff, but never retries a 404, and
    leaves NO file behind on any non-200 (removes 404 error-xml / partial bodies). this
    http-code-aware classification is what stops a transient failure from being silently
    treated as an 'air' (blank) chunk -- the bug that corrupted the aria2c/runpod volumes."""
    code = "000"
    for _i in range(max(1, tries)):
        r = subprocess.run(
            ["curl", "-s", "--connect-timeout", "20", "--max-time", "120",
             "-o", out, "-w", "%{http_code}", url], capture_output=True)
        code = (r.stdout.decode("utf-8", "ignore").strip() or "000")[-3:]
        if code == "200":
            return code
        if os.path.exists(out):
            try: os.remove(out)
            except OSError: pass
        if code == "404":
            return code
        time.sleep(1)                 # transient -> brief backoff, then retry
    return code


def _fetch_chunk(args):
    """download one chunk. 200 -> data file; 404 -> zero-byte air sentinel; any OTHER failure
    -> NO file left, so _verify_repair re-checks/aborts instead of silently blanking it."""
    base, level, yc, xc, cache_dir = args
    out = os.path.join(cache_dir, f"{level}_{yc}_{xc}.raw")
    if os.path.exists(out):
        return (yc, xc, "cached")
    code = _curl_code(f"{base}/{level}/0/{yc}/{xc}", out)
    if code == "200":
        return (yc, xc, "ok")
    if code == "404":
        open(out, "wb").close()       # confirmed air
        return (yc, xc, "air")
    return (yc, xc, "fail")           # transient -> leave missing for _verify_repair


def _load_chunk(cache_dir, level, yc, xc, D):
    p = os.path.join(cache_dir, f"{level}_{yc}_{xc}.raw")
    try:
        if os.path.getsize(p) == D * CHUNK_XY * CHUNK_XY:
            return np.frombuffer(open(p, "rb").read(), dtype=np.uint8).reshape(D, CHUNK_XY, CHUNK_XY)
    except Exception:
        pass
    return None


def _aria2_fetch(base, level, jobs, cache_dir, workers):
    """bulk-download all not-yet-cached chunks with ONE aria2c process (fast, connection reuse).
    aria2c CANNOT distinguish a 404 from a transient failure, so it writes NO air sentinels here
    -- _verify_repair afterwards http-code-classifies everything aria2c left missing. returns
    (success_bool, elapsed_seconds)."""
    if shutil.which("aria2c") is None:
        return False, 0
    todo = [(f"{base}/{level}/0/{yc}/{xc}", f"{level}_{yc}_{xc}.raw")
            for (_b, _lvl, yc, xc, _cd) in jobs
            if not os.path.exists(os.path.join(cache_dir, f"{level}_{yc}_{xc}.raw"))]
    if not todo:
        return True, 0
    listfile = os.path.join(cache_dir, "_aria2_urls.txt")
    with open(listfile, "w") as f:
        for url, name in todo:
            f.write(f"{url}\n  dir={cache_dir}\n  out={name}\n")
    j = max(1, min(int(workers), 64))
    print(f"[dl] aria2c: bulk-fetching {len(todo)} chunks with -j{j} (missing chunks verified below)...", flush=True)
    t0 = time.time()
    subprocess.run(
        ["aria2c", "-i", listfile, f"-j{j}", "-x1", "-s1",
         "--max-tries=2", "--retry-wait=1", "--connect-timeout=20", "--timeout=120",
         "--auto-file-renaming=false", "--allow-overwrite=true",
         "-q", "--download-result=hide"],
        check=False)
    elapsed = time.time() - t0
    try:
        os.remove(listfile)
    except OSError:
        pass
    return True, elapsed


def _verify_repair(base, level, jobs, cache_dir, D, workers):
    """CORRECTNESS GATE. verify every expected chunk is EITHER a correctly-sized data file OR a
    confirmed-404 air chunk (zero-byte sentinel). anything missing or wrong-sized is re-fetched
    with an http-code-aware curl and classified 200->data / 404->air / else->hard failure. raises
    RuntimeError if any chunk cannot be resolved -- we refuse to assemble a silently-blanked
    volume (better to fail loudly and retry than train on corrupt data). returns (data, air)."""
    expected = D * CHUNK_XY * CHUNK_XY
    need = []
    data_n = air_n = 0
    for (_b, _lvl, yc, xc, _cd) in jobs:
        p = os.path.join(cache_dir, f"{level}_{yc}_{xc}.raw")
        if os.path.exists(p):
            sz = os.path.getsize(p)
            if sz == expected:
                data_n += 1; continue          # valid data
            if sz == 0:
                air_n += 1; continue           # confirmed-404 air sentinel
            try: os.remove(p)                  # partial/corrupt -> re-fetch
            except OSError: pass
        need.append((yc, xc))
    if need:
        print(f"[dl] verify: re-checking {len(need)} missing/partial chunk(s) with http-code...", flush=True)
        def _chk(coord):
            yc, xc = coord
            p = os.path.join(cache_dir, f"{level}_{yc}_{xc}.raw")
            code = _curl_code(f"{base}/{level}/0/{yc}/{xc}", p, tries=4)
            if code == "200" and os.path.exists(p) and os.path.getsize(p) == expected:
                return (coord, "data")
            if code == "404":
                open(p, "wb").close()
                return (coord, "air")
            return (coord, f"ERR:{code}")
        results = {}
        with ThreadPoolExecutor(max_workers=max(1, min(int(workers), 32))) as ex:
            for coord, status in ex.map(_chk, need):
                results[coord] = status
        errs = [(c, s) for c, s in results.items() if s.startswith("ERR")]
        if errs:
            raise RuntimeError(
                f"[dl] {len(errs)} chunk(s) failed to download for a NON-404 reason, e.g. {errs[:5]}. "
                f"refusing to assemble a blanked volume -- re-run to retry (S3 may be rate-limiting).")
        data_n += sum(1 for s in results.values() if s == "data")
        air_n += sum(1 for s in results.values() if s == "air")
    return data_n, air_n


def _download_surface_zarr(base, level, out_zarr, out_id, workers, cache_dir, chunk_depth, chunk_y, chunk_x):
    """download a pre-rendered OME-Zarr surface volume from S3 -> local zarr + mask png.
    these segment surface-volumes are ALREADY flattened (no mesh sampling needed), stored as
    OME-Zarr: a group with pyramid levels 0..5, each an array with chunks [D,128,128], uint8,
    NO compressor, dimension_separator "/". a chunk lives at  {base}.zarr/{level}/{zc}/{yc}/{xc}.
    the chunk depth == full D, so zc is always 0; missing chunk (404) = all-air background."""
    base = base.rstrip("/")
    za = _get_json(f"{base}/{level}/.zarray")
    D, H, W = za["shape"]
    print(f"[dl] level {level} shape (D,H,W)=({D},{H},{W}) dtype={za['dtype']}")
    os.makedirs(cache_dir, exist_ok=True)

    n_yc = (H + CHUNK_XY - 1) // CHUNK_XY
    n_xc = (W + CHUNK_XY - 1) // CHUNK_XY
    jobs = [(base, level, yc, xc, cache_dir) for yc in range(n_yc) for xc in range(n_xc)]
    print(f"[dl] fetching {len(jobs)} chunks ({n_yc}x{n_xc}) with {workers} workers "
          f"(~{len(jobs) * D * CHUNK_XY * CHUNK_XY / 1e9:.1f} GB max)")
    
    # fast path: single aria2c process (connection reuse). falls back to per-chunk curl if absent.
    used_aria2, aria2_time = _aria2_fetch(base, level, jobs, cache_dir, workers)
    if used_aria2 and aria2_time > 0:
        print(f"[dl] aria2c completed in {aria2_time:.1f}s ({aria2_time/60:.1f}m)", flush=True)
    
    if not used_aria2:
        done = 0
        with ThreadPoolExecutor(max_workers=workers) as ex:
            for _ in ex.map(_fetch_chunk, jobs):
                done += 1
                if done % 500 == 0:
                    print(f"[dl] fetched {done}/{len(jobs)}", flush=True)
    
    # CORRECTNESS GATE: verify every chunk is valid data or a confirmed-404 air chunk, re-fetching
    # anything missing/partial and ABORTING on a non-404 failure. this is what stops a transient
    # download error from being silently baked into the volume as a blank region.
    data_n, air_n = _verify_repair(base, level, jobs, cache_dir, D, workers)
    print(f"[dl] all {len(jobs)} chunks verified: {data_n} data + {air_n} air (blank)", flush=True)

    # write zarr directly from cache chunks (avoids ~2GB intermediate array).
    # writing full-z columns means each zarr z-chunk gets all its data in one shot,
    # eliminating the read-modify-write that layer-by-layer writes cause (~7x redundant
    # reads per z-chunk group). columns are disjoint in zarr chunk space and mask space,
    # so parallel writes are safe with DirectoryStore (one file per chunk, no shared state).
    import zarr
    store = zarr.open(out_zarr, mode="w", shape=(D, H, W), 
                      chunks=(min(chunk_depth, D), chunk_y, chunk_x),
                      dtype="<u2", compressor=None, zarr_format=2)
    mask_buf = np.zeros((H, W), dtype=np.uint8)

    def _write_col(yx):
        yc, xc = yx
        ch = _load_chunk(cache_dir, level, yc, xc, D)
        y0, x0 = yc * CHUNK_XY, xc * CHUNK_XY
        y1, x1 = min(y0 + CHUNK_XY, H), min(x0 + CHUNK_XY, W)
        if ch is None:
            return
        data = ch[:, :y1-y0, :x1-x0]
        store[:, y0:y1, x0:x1] = data.astype(np.uint16)
        mask_buf[y0:y1, x0:x1] = (data.max(axis=0) > 0).astype(np.uint8) * 255

    pairs = [(yc, xc) for yc in range(n_yc) for xc in range(n_xc)]
    upd, close = _pbar(len(pairs), "writing zarr")
    # 32 threads is a practical sweet spot: more causes small-file write contention
    with ThreadPoolExecutor(max_workers=min(workers, 32)) as ex:
        for _ in ex.map(_write_col, pairs):
            upd()
    close()
    print(f"[dl] wrote zarr {out_zarr} ({D},{H},{W}) uint16")

    # mask = footprint where ANY layer is nonzero (valid rendered surface)
    os.makedirs("masks", exist_ok=True)
    Image.fromarray(mask_buf).save(f"masks/{out_id}.png")
    print(f"[dl] wrote masks/{out_id}.png  valid_frac={(mask_buf > 0).mean():.3f}")


def _verify_zarr_integrity(zarr_path, zid):
    """post-download integrity check: verify all depth slices have valid (non-zero) data.
    raises RuntimeError if the volume appears corrupted/incomplete (e.g., only first few
    slices downloaded, rest are zeros). this catches the bug that corrupted w044/w034."""
    import zarr
    print(f"[verify] checking zarr integrity: {zarr_path}", flush=True)
    try:
        z = zarr.open(zarr_path, mode='r')
        D, H, W = z.shape
        
        # check every depth slice for valid data (sample a stripe across middle)
        valid_depths = []
        for d in range(D):
            # sample every 100th pixel across middle row to avoid loading full slice
            sample = z[d, H//2, ::100]
            if sample.mean() > 0 and len(np.unique(sample)) > 1:
                valid_depths.append(d)
        
        valid_count = len(valid_depths)
        coverage = valid_count / D if D > 0 else 0
        
        print(f"[verify] {zid}: {valid_count}/{D} depths have valid data ({coverage*100:.1f}%)")
        
        # require at least 90% depth coverage (allow a few air slices at edges)
        if coverage < 0.90:
            missing = sorted(set(range(D)) - set(valid_depths))
            raise RuntimeError(
                f"INTEGRITY CHECK FAILED: {zid} has only {valid_count}/{D} valid depths "
                f"({coverage*100:.1f}% coverage). Missing/zero depths: {missing[:10]}{'...' if len(missing) > 10 else ''}. "
                f"This indicates an incomplete download. Delete {zarr_path} and re-run to retry.")
        
        # check spatial coverage on middle depth slice
        mid_d = D // 2
        if mid_d in valid_depths:
            # sample 10x10 regions at 5 locations
            regions = [
                z[mid_d, H//4:H//4+10, W//4:W//4+10],
                z[mid_d, H//4:H//4+10, 3*W//4:3*W//4+10],
                z[mid_d, H//2:H//2+10, W//2:W//2+10],
                z[mid_d, 3*H//4:3*H//4+10, W//4:W//4+10],
                z[mid_d, 3*H//4:3*H//4+10, 3*W//4:3*W//4+10],
            ]
            nonzero_regions = sum(1 for r in regions if r.mean() > 0)
            if nonzero_regions == 0:
                raise RuntimeError(
                    f"INTEGRITY CHECK FAILED: {zid} depth {mid_d} has no valid data in sampled regions. "
                    f"Volume may be corrupted. Delete {zarr_path} and re-run.")
        
        print(f"[verify] ✓ {zid} integrity check passed", flush=True)
        
    except Exception as e:
        if "INTEGRITY CHECK FAILED" in str(e):
            raise
        raise RuntimeError(f"Failed to verify zarr integrity for {zid}: {e}")


def step1_volume(name, seg, zid, workers, chunk_depth, chunk_y, chunk_x):
    # w013 uses a dedicated assembly script (level-2 surface zarr, z-pooled to 28 layers)
    if FRAG_OPTS.get(name, {}).get("custom_assemble"):
        zpath = os.path.join(ZARR_DIR, f"{zid}.zarr")
        mpath = f"masks/{zid}.png"
        if os.path.exists(zpath) and os.path.exists(mpath):
            print(f"  [1/3] volume+mask exist -> skip")
            return
        run([sys.executable, "assemble_w013_1667.py", "--skip-norm"])
        return
    zpath = os.path.join(ZARR_DIR, f"{zid}.zarr")
    mpath = f"masks/{zid}.png"
    if os.path.exists(zpath) and os.path.exists(mpath):
        print(f"  [1/3] volume+mask exist -> skip")
        return
    # per-fragment volume name override (non-PHerc0139 scrolls have a different raw vol id)
    vol9 = FRAG_OPTS.get(name, {}).get("vol9_name", VOL9_NAME)
    url = f"{BUCKET}/{seg}/surface-volumes/{vol9}"
    cache = os.path.join(TMP, f"dl_{zid}")
    _download_surface_zarr(url, level=0, out_zarr=zpath, out_id=zid, 
                           workers=workers, cache_dir=cache,
                           chunk_depth=chunk_depth, chunk_y=chunk_y, chunk_x=chunk_x)
    
    # INTEGRITY CHECK: verify all depth slices have valid data (catches incomplete downloads)
    _verify_zarr_integrity(zpath, zid)


def step2_check_eroded_labels(name, seg, zid):
    """verify eroded_inklabels exist (the only labels we actually use for training).
    these are pre-generated conservative binary labels: high-confidence ink pixels,
    eroded and masked. the inklabels/ dir (raw 1um ink detection) is NOT used."""
    eroded_path = f"eroded_inklabels/{zid}.png"
    if os.path.exists(eroded_path):
        # check it's not empty/corrupt
        try:
            img = np.array(Image.open(eroded_path).convert("L"))
            valid_frac = (img > 0).mean()
            print(f"  [2/3] eroded labels present: {eroded_path}  valid={valid_frac:.4f}")
            return
        except Exception as e:
            print(f"  [2/3] \033[91m!! ERROR: eroded label exists but failed to load: {e}\033[0m")
            return
    
    # MISSING eroded labels -> big red warning
    print(f"  [2/3] \033[91m{'='*60}")
    print(f"  !! WARNING: MISSING ERODED LABEL FILE !!")
    print(f"  Expected: {eroded_path}")
    print(f"  This fragment CANNOT be used for training without labels.")
    print(f"  Eroded labels must be pre-generated (e.g., from 1um ink detection)")
    print(f"  and placed in eroded_inklabels/ before running training.")
    print(f"  {'='*60}\033[0m")


def step3_norm(name, seg, zid, skip):
    if skip:
        print(f"  [3/3] --skip-norm -> skip")
        return
    import json
    if os.path.exists("norm_cache.json"):
        try:
            if zid in json.load(open("norm_cache.json")):
                print(f"  [3/3] norm cached -> skip")
                return
        except Exception:
            pass
    run([sys.executable, "precompute_norm.py", "--scroll-id", zid, "--zarr-path", ZARR_DIR])


def process_fragment(name, seg, zid, workers, skip_norm, chunk_depth, chunk_y, chunk_x, prefix=""):
    """run the full assembly pipeline for one fragment. isolated in try/except so a
    single failure never kills a concurrent batch. respects FRAG_OPTS (skip_labels)."""
    opts = FRAG_OPTS.get(name, {})
    tag = f"{prefix}{name} ({zid})"
    try:
        print(f"\n{'='*70}\n{tag}  id={zid}\n{'='*70}", flush=True)
        step1_volume(name, seg, zid, workers, chunk_depth, chunk_y, chunk_x)
        if not opts.get("skip_labels"):
            step2_check_eroded_labels(name, seg, zid)
        else:
            print(f"  [labels] skip_labels -> keeping existing eroded_inklabels")
        step3_norm(name, seg, zid, skip_norm)
        print(f"[done] {tag}")
        return (name, "OK")
    except Exception as e:
        import traceback
        print(f"[FAIL] {tag}: {e}")
        traceback.print_exc()
        return (name, f"FAIL: {e}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", type=str, default=None)
    ap.add_argument("--from", dest="from_name", type=str, default=None)
    ap.add_argument("--workers", type=int, default=32,
                    help="parallel S3 chunk-download workers PER fragment (default 32 for EPYC 7702)")
    ap.add_argument("--concurrent-fragments", type=int, default=5,
                    help="number of fragments to assemble in parallel (default 5). "
                         "each uses --workers download threads, so total connections "
                         "= concurrent_fragments * workers; watch RAM (~2-5GB per fragment).")
    ap.add_argument("--skip-norm", action="store_true")
    ap.add_argument("--chunk-depth", type=int, default=DEFAULT_CHUNK_DEPTH,
                    help=f"zarr depth chunk size (default {DEFAULT_CHUNK_DEPTH}, optimized for 8-slice windows)")
    ap.add_argument("--chunk-y", type=int, default=DEFAULT_CHUNK_Y,
                    help=f"zarr Y chunk size (default {DEFAULT_CHUNK_Y})")
    ap.add_argument("--chunk-x", type=int, default=DEFAULT_CHUNK_X,
                    help=f"zarr X chunk size (default {DEFAULT_CHUNK_X})")
    args = ap.parse_args()

    segs = SEGMENTS
    if args.only:
        segs = [s for s in SEGMENTS if s[0] == args.only]
    elif args.from_name:
        names = [s[0] for s in SEGMENTS]
        segs = SEGMENTS[names.index(args.from_name):]

    cf = max(1, int(args.concurrent_fragments))
    print(f"[assemble] {len(segs)} fragment(s): {[s[0] for s in segs]}  "
          f"(concurrent_fragments={cf}, workers/frag={args.workers}, "
          f"chunks=({args.chunk_depth},{args.chunk_y},{args.chunk_x}))")

    results = []
    if cf == 1:
        for name, seg, zid in segs:
            results.append(process_fragment(name, seg, zid, args.workers, args.skip_norm,
                                          args.chunk_depth, args.chunk_y, args.chunk_x))
    else:
        from concurrent.futures import ThreadPoolExecutor, as_completed
        with ThreadPoolExecutor(max_workers=cf) as ex:
            futs = {ex.submit(process_fragment, name, seg, zid, args.workers,
                              args.skip_norm, args.chunk_depth, args.chunk_y, args.chunk_x,
                              prefix=f"[{name}] "): name
                    for name, seg, zid in segs}
            for fut in as_completed(futs):
                results.append(fut.result())

    print(f"\n{'='*70}\n[assemble] SUMMARY\n{'='*70}")
    for nm, status in results:
        print(f"  {nm}: {status}")


if __name__ == "__main__":
    main()
